'use client';
import {useRef,useState}from'react';
import {Download,Upload,ChevronLeft,SlidersHorizontal}from'lucide-react';
export default function Home(){
 const [open,setOpen]=useState(false),[name,setName]=useState('वेतन गोदारा'),[role,setRole]=useState('RLP युवा साथी'),[place,setPlace]=useState('ग्राम पंचायत नौखड़ा बेरी'),[phone,setPhone]=useState('7742494320'),[photo,setPhoto]=useState(''),[leader,setLeader]=useState(''),[msg,setMsg]=useState('आपका हार्दिक अभिनंदन');
 const canvas=useRef<HTMLCanvasElement>(null);
 const pick=(set:(s:string)=>void,f?:File)=>{if(!f)return;const r=new FileReader();r.onload=()=>set(String(r.result));r.readAsDataURL(f)};
 const download=()=>{const c=canvas.current!,x=c.getContext('2d')!;c.width=1080;c.height=1350;x.fillStyle='#041c0a';x.fillRect(0,0,1080,1350);
 const T=(s:string,a:number,b:number,n:number,col:string,al:CanvasTextAlign='left')=>{x.fillStyle=col;x.textAlign=al;x.font='900 '+n+'px Arial';x.fillText(s,a,b)};
 x.fillStyle='#fff';x.beginPath();x.arc(110,108,82,0,7);x.fill();x.lineWidth=10;x.strokeStyle='#f2cf24';x.beginPath();x.arc(110,108,82,.5,3.7);x.stroke();x.strokeStyle='#397d2f';x.beginPath();x.arc(110,108,82,3.7,6.8);x.stroke();T('राष्ट्रीय लोकतांत्रिक पार्टी',210,68,31,'#f4f4f1');T('RLP',210,126,52,'#ffd429');T('हनुमान बेनीवाल',210,171,27,'#f4f4f1');T('के निर्देश में',210,205,27,'#f4f4f1');
 x.strokeStyle='#7cae12';for(let i=0;i<14;i++){x.lineWidth=13+i*3;x.beginPath();x.moveTo(650+i*18,290+i*5);x.lineTo(1090,70+i*26);x.stroke()}
 const w=msg.split(' ');T(w[0]||'आपका',42,350,76,'#fff');T(w[1]||'हार्दिक',42,465,105,'#ffd42a');T(w.slice(2).join(' ')||'अभिनंदन',42,555,68,'#fff');T('जय जवान जय किसान',42,650,29,'#f5f5ef');
 const finish=()=>{x.fillStyle='#ffd229';x.fillRect(0,930,1080,215);T(name,525,1045,88,'#612100','center');T(role,525,1105,33,'#173b18','center');x.fillStyle='#082b0f';x.roundRect(750,965,270,140,14);x.fill();T('RLP',885,1010,42,'#ffd229','center');T('युवा साथी',885,1060,34,'#fff','center');x.fillStyle='#f3f2ed';x.fillRect(0,1145,1080,105);T('☎',120,1215,47,'#25813d','center');T(phone,540,1218,56,'#15351d','center');x.fillStyle='#08230d';x.fillRect(0,1250,1080,100);T('राष्ट्रीय लोकतांत्रिक पार्टी (RLP)',55,1312,27,'#ffd229');T('चुनाव चिन्ह - बोतल',1020,1312,25,'#fff','right');const a=document.createElement('a');a.href=c.toDataURL('image/png');a.download='rlp-poster.png';a.click()};
 const cover=(i:HTMLImageElement,dx:number,dy:number,dw:number,dh:number)=>{const z=Math.max(dw/i.width,dh/i.height),iw=i.width*z,ih=i.height*z;x.drawImage(i,dx+(dw-iw)/2,dy+(dh-ih)/2,iw,ih)};
 const user=()=>{if(!photo)return finish();const i=new Image();i.onload=()=>{x.save();x.beginPath();x.roundRect(155,330,610,600,25);x.clip();cover(i,155,330,610,600);x.restore();finish()};i.src=photo};
 if(!leader)return user();const l=new Image();l.onload=()=>{x.save();x.beginPath();x.roundRect(610,190,450,740,30);x.clip();cover(l,610,190,450,740);x.restore();user()};l.src=leader;
 };
 if(!open)return <main className="app"><header><b><i>RLP</i> Poster Maker</b></header><section className="landing"><div className="ref"><div className="sampleTop"><b>RLP</b><span>राष्ट्रीय लोकतांत्रिक पार्टी</span></div><div className="sampleText">आपका<br/><strong>हार्दिक</strong><br/>अभिनंदन</div><div className="sampleBrush"/><div className="sampleLeader"/><div className="sampleUser"/><div className="sampleBand">वेतन गोदारा</div><div className="samplePhone">☎ 7742494320</div></div><h1>Same Poster Template</h1><p>ऊपर identity, left text, पीछे leader, आगे user, yellow name band, contact strip और footer—सब इसी layout में।</p><button className="start" onClick={()=>setOpen(true)}>Use This Exact Layout</button></section></main>;
 return <main className="app"><canvas ref={canvas} hidden/><header><button className="back" onClick={()=>setOpen(false)}><ChevronLeft/> Templates</button><b><i>RLP</i> Editable Poster</b></header><section className="editor"><div className="controls"><div className="title"><SlidersHorizontal/> Poster Details</div><label>मुख्य संदेश<input value={msg} onChange={e=>setMsg(e.target.value)}/></label><label>आपका नाम<input value={name} onChange={e=>setName(e.target.value)}/></label><label>पद / पहचान<input value={role} onChange={e=>setRole(e.target.value)}/></label><label>स्थान<input value={place} onChange={e=>setPlace(e.target.value)}/></label><label>मोबाइल नंबर<input value={phone} onChange={e=>setPhone(e.target.value)}/></label><label className="upload"><input type="file" accept="image/*" onChange={e=>pick(setPhoto,e.target.files?.[0])}/><Upload/> Main Photo {photo&&'✓'}</label><label className="upload"><input type="file" accept="image/*" onChange={e=>pick(setLeader,e.target.files?.[0])}/><Upload/> Leader Photo {leader&&'✓'}</label><button className="download" onClick={download}><Download/> Download Poster</button></div><div className="stage"><div className="poster"><div className="logo">▯</div><div className="identity"><b>राष्ट्रीय लोकतांत्रिक पार्टी</b><strong>RLP</strong><small>हनुमान बेनीवाल<br/>के निर्देश में</small></div><div className="brush"/><div className="welcome">{msg.split(' ').map((v,i)=><div key={i} className={'w w'+i}>{v}</div>)}<small>जय जवान जय किसान</small></div>{leader?<img className="leaderPic" src={leader}/>:<div className="leaderPlaceholder">LEADER PHOTO</div>}{photo?<img className="userPic" src={photo}/>:<div className="userPlaceholder">YOUR PHOTO</div>}<div className="symbol">▯<b>चुनाव चिन्ह<br/>बोतल</b></div><div className="nameBand"><div><b>{name}</b><small>{role}</small></div><aside><b>RLP</b><span>युवा साथी</span><em>{place}</em></aside></div><div className="contact">☎ <b>{phone}</b></div><div className="footer">राष्ट्रीय लोकतांत्रिक पार्टी (RLP) <span/> चुनाव चिन्ह - बोतल</div></div></div></section></main>
}